/* Valeria Quesada Benavides*/
/*These code was executed in Snowflake worksheets.*/

/*Temporary table cleaning repeated data by distinct function*/
CREATE TEMPORARY TABLE TRANSACTIONSCOPY
AS SELECT DISTINCT TRANSACTIONS.* FROM TRANSACTIONS;

/*Function that deletes special characters with column name parameter*/
CREATE OR REPLACE PROCEDURE UPDATESPECIALCHARACTERS(COLUMNNAME TEXT)
RETURNS INT
LANGUAGE SQL
AS
BEGIN
    /*SQL code that indicates that every _ has to be changed with the blank space*/
    EXECUTE IMMEDIATE 'UPDATE TRANSACTIONSCOPY SET ' || COLUMNNAME || ' = REPLACE(TRANSLATE(' || COLUMNNAME || ', ''_'', '' ''), '' '', '' '')';
    SELECT * FROM TRANSACTIONSCOPY;
    RETURN 0; /*End of the excecution*/
END;

/*Calls for the UPDATESPECIALCHARACTERS procedure*/
CALL UPDATESPECIALCHARACTERS('CLIENT_NAME');
CALL UPDATESPECIALCHARACTERS('CLIENT_LASTNAME');
CALL UPDATESPECIALCHARACTERS('STORE_NAME');
CALL UPDATESPECIALCHARACTERS('LOCATION');
CALL UPDATESPECIALCHARACTERS('PRODUCT_NAME');
CALL UPDATESPECIALCHARACTERS('BRAND');
CALL UPDATESPECIALCHARACTERS('STREET');
CALL UPDATESPECIALCHARACTERS('CITY');
CALL UPDATESPECIALCHARACTERS('STATE');

/*Reads all the table looking for values
  If its varchar null is replaced with NOT FOUND
  If its number ot int is replaced with 0*/
UPDATE TRANSACTIONSCOPY
SET 
    CLIENT_NAME = COALESCE(CLIENT_NAME, 'NOT FOUND'),
    CLIENT_LASTNAME = COALESCE(CLIENT_LASTNAME, 'NOT FOUND'),
    EMAIL = COALESCE(EMAIL, 'NOT FOUND'),
    STORE_ID = COALESCE(STORE_ID, 0),
    STORE_NAME = COALESCE(STORE_NAME, 'NOT FOUND'),
    LOCATION = COALESCE(LOCATION, 'NOT FOUND'),
    PRODUCT_ID = COALESCE(PRODUCT_ID, 0),
    PRODUCT_NAME = COALESCE(PRODUCT_NAME, 'NOT FOUND'),
    CATEGORY = COALESCE(CATEGORY, 'NOT FOUND'),
    BRAND = COALESCE(BRAND, 'NOT FOUND'),
    ADDRESS_ID = COALESCE(ADDRESS_ID, 0),
    STREET = COALESCE(STREET, 'NOT FOUND'),
    CITY = COALESCE(CITY, 'NOT FOUND'),
    STATE = COALESCE(STATE, 'NOT FOUND'),
    ZIP_CODE = COALESCE(ZIP_CODE, 0),
    TRANSACTION_ID = COALESCE(TRANSACTION_ID, 0),
    QUANTITY_OF_ITEMS_SOLD = COALESCE(QUANTITY_OF_ITEMS_SOLD, 0),
    UNIT_PRICE = COALESCE(UNIT_PRICE, 0),
    DISCOUNT = COALESCE(DISCOUNT, 0)
WHERE CLIENT_NAME IS NULL OR CLIENT_LASTNAME IS NULL OR
      EMAIL IS NULL OR STORE_ID IS NULL OR
      STORE_NAME IS NULL OR LOCATION IS NULL OR
      PRODUCT_ID IS NULL OR PRODUCT_NAME IS NULL OR
      CATEGORY IS NULL OR BRAND IS NULL OR
      ADDRESS_ID IS NULL OR STREET IS NULL OR
      CITY IS NULL OR STATE IS NULL OR
      ZIP_CODE IS NULL OR TRANSACTION_ID IS NULL OR
      QUANTITY_OF_ITEMS_SOLD IS NULL OR UNIT_PRICE IS NULL OR
      DISCOUNT IS NULL;

/*Cleans transaction table*/
DELETE FROM TRANSACTIONS;

/*Insert updated data from TRANSACTIONSCOPY to TRANSACTION Table*/
INSERT INTO TRANSACTIONS
SELECT * FROM TRANSACTIONSCOPY;

/*Deletes TRANSACTIONSCOPY Table*/
DROP TABLE TRANSACTIONSCOPY;
